-- Вставляем тестовые задачи
-- INSERT INTO tasks
-- (name, user_id, weight, add_to_sum, start_value, target_value, type_id)
-- VALUES
--     ('add', 1,  0.3, TRUE, 50, 250, 1),
--     ('replace', 1, 0.7, FALSE, 400, 700, 1);